'use strict';

/**
 * services/email.js
 *
 * Sends the audit result email to the requester.
 * Skips silently when EMAIL_HOST is not set (local dev / CI).
 *
 * Usage:
 *   const { sendAuditResult } = require('./services/email');
 *   await sendAuditResult({ to, url, score, categoryScores, summary });
 */

const nodemailer = require('nodemailer');

// ── Transport — created lazily so missing env vars don't crash on startup ─────

let _transporter = null;

function getTransporter() {
  if (_transporter) return _transporter;

  const { EMAIL_HOST, EMAIL_PORT, EMAIL_USER, EMAIL_PASS } = process.env;
  if (!EMAIL_HOST) return null;

  _transporter = nodemailer.createTransport({
    host:   EMAIL_HOST,
    port:   parseInt(EMAIL_PORT || '587', 10),
    secure: parseInt(EMAIL_PORT || '587', 10) === 465,
    auth:   EMAIL_USER ? { user: EMAIL_USER, pass: EMAIL_PASS } : undefined,
  });

  return _transporter;
}

// ── Grade helper ──────────────────────────────────────────────────────────────

function gradeOf(score) {
  if (score >= 90) return 'A';
  if (score >= 80) return 'B';
  if (score >= 70) return 'C';
  if (score >= 60) return 'D';
  return 'F';
}

// ── HTML template ─────────────────────────────────────────────────────────────

function buildHtml({ url, score, grade, categoryScores, summary }) {
  const gradeColor = { A: '#2e7d32', B: '#558b2f', C: '#f9a825', D: '#e65100', F: '#c62828' };
  const color = gradeColor[grade] || '#111';

  const categoryRows = Object.entries(categoryScores)
    .map(([cat, s]) => {
      const g     = gradeOf(s);
      const label = cat.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      const col   = gradeColor[g] || '#111';
      return `
        <tr>
          <td style="padding:6px 12px;border-bottom:1px solid #e0e0e0;font-size:14px">${label}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #e0e0e0;font-size:14px;font-weight:700;color:${col};text-align:right">${s} · ${g}</td>
        </tr>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:system-ui,-apple-system,sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;padding:32px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e0e0e0;max-width:600px;width:100%">

        <!-- Header -->
        <tr>
          <td style="padding:28px 32px 20px;border-bottom:1px solid #e0e0e0">
            <p style="margin:0;font-size:13px;color:#666;font-weight:600;text-transform:uppercase;letter-spacing:.06em">Devies — Site Health Checker</p>
            <h1 style="margin:8px 0 0;font-size:22px;font-weight:700;color:#111">Here is the result for your audit request</h1>
          </td>
        </tr>

        <!-- Score -->
        <tr>
          <td style="padding:28px 32px 20px;border-bottom:1px solid #e0e0e0;text-align:center">
            <p style="margin:0 0 4px;font-size:13px;color:#666">${url}</p>
            <p style="margin:8px 0 4px;font-size:56px;font-weight:800;line-height:1;color:${color}">${score}</p>
            <p style="margin:0;font-size:20px;font-weight:700;color:${color}">Grade ${grade}</p>
            <p style="margin:16px 0 0;font-size:14px;color:#444;max-width:460px;margin-left:auto;margin-right:auto;line-height:1.6">${summary}</p>
          </td>
        </tr>

        <!-- Category breakdown -->
        <tr>
          <td style="padding:20px 32px 0">
            <p style="margin:0 0 12px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:#666">Category Breakdown</p>
            <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e0e0e0">
              ${categoryRows}
            </table>
          </td>
        </tr>

        <!-- CTA -->
        <tr>
          <td style="padding:24px 32px 32px">
            <p style="margin:0 0 16px;font-size:14px;color:#444;line-height:1.6">
              Want help improving your website? Our team can walk you through the findings and implement the fixes for you.
            </p>
            <a href="mailto:hello@devies.se" style="display:inline-block;padding:12px 24px;background:#111;color:#fff;font-size:14px;font-weight:600;text-decoration:none">
              Contact us →
            </a>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:16px 32px;border-top:1px solid #e0e0e0;background:#f5f5f5">
            <p style="margin:0;font-size:12px;color:#999">
              This report was generated by the Devies Site Health Checker. You are receiving this because you submitted a website audit request.
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildText({ url, score, grade, categoryScores, summary }) {
  const cats = Object.entries(categoryScores)
    .map(([cat, s]) => {
      const label = cat.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      return `  ${label}: ${s} (${gradeOf(s)})`;
    })
    .join('\n');

  return `Here is the result for your audit request

URL: ${url}
Overall Score: ${score} — Grade ${grade}

${summary}

Category Breakdown:
${cats}

---
Want help improving your website? Contact us at hello@devies.se

This report was generated by the Devies Site Health Checker.`;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * @param {object} opts
 * @param {string} opts.to              Recipient email address
 * @param {string} opts.url             Audited URL
 * @param {number} opts.score           Overall score (0–100)
 * @param {Record<string,number>} opts.categoryScores
 * @param {string} opts.summary         Interpretation summary
 */
async function sendAuditResult({ to, url, score, categoryScores, summary }) {
  const transport = getTransporter();
  if (!transport) return; // EMAIL_HOST not configured — skip silently

  const grade   = gradeOf(score);
  const from    = process.env.EMAIL_FROM || '"Devies Audit" <audit@devies.se>';

  let hostname;
  try { hostname = new URL(url).hostname; } catch { hostname = url; }

  await transport.sendMail({
    from,
    to,
    subject: `Your website audit result for ${hostname}`,
    text:    buildText({ url, score, grade, categoryScores, summary }),
    html:    buildHtml({ url, score, grade, categoryScores, summary }),
  });
}

module.exports = { sendAuditResult };
